# Generated by Django 4.2.11 on 2024-05-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('watering_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('sunlight_preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('pruning_information', models.TextField(blank=True, null=True)),
                ('seeds', models.TextField(blank=True, null=True)),
                ('propagation_methods', models.TextField(blank=True, null=True)),
                ('hardiness_zones', models.CharField(blank=True, max_length=255, null=True)),
                ('flowers', models.TextField(blank=True, null=True)),
                ('fruits', models.TextField(blank=True, null=True)),
                ('foliage', models.TextField(blank=True, null=True)),
                ('care_level', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
