# Generated by Django 4.2.11 on 2024-06-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField()),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('section', models.JSONField()),
            ],
        ),
    ]
