# Generated by Django 4.2.11 on 2024-06-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plantdisease_plantguide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantGuide',
        ),
    ]
