# Generated by Django 4.2.11 on 2024-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_plantguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='plantdisease',
            old_name='solution',
            new_name='control_methods',
        ),
        migrations.RemoveField(
            model_name='plantdisease',
            name='family',
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdisease',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
