# Generated by Django 4.2.11 on 2024-06-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('guide_type', models.CharField(blank=True, max_length=50, null=True)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='api.species')),
            ],
        ),
    ]
