# Generated by Django 4.2.11 on 2024-06-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_plantguide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantGuide',
        ),
    ]
