# Generated by Django 4.2.11 on 2024-06-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_careguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careguide',
            name='type',
        ),
        migrations.CreateModel(
            name='CareGuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('care_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.careguide')),
            ],
        ),
    ]
