# Generated by Django 4.2.11 on 2024-06-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_careguide_type_careguidesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='careguide',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CareGuideSection',
        ),
    ]
