# Generated by Django 4.2.11 on 2024-06-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_careguide_type_delete_careguidesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareGuide',
        ),
    ]
