# Generated by Django 4.2.11 on 2024-06-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
