# Generated by Django 4.2.11 on 2024-06-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_plantactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantActivity',
        ),
    ]
