# Generated by Django 4.2.11 on 2024-06-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_plantactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fertilizing_reminder_period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_fertilizing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_pruning_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_sunlight_exposure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_watered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_reminder_period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pruning_reminder_period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight_exposure_reminder_period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_reminder_period',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
